apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::362114946245:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-AUY38GR8HX5A
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::362114946245:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-24T08:25:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "823"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f0b1a8ac-d902-4203-abd3-af3b48fad570
