apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
    - rolearn: arn:aws:iam::362114946245:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters

